### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by aadeshnpn** [Kautenja/playing-mario-with-deep-reinforcement-learning#35]
train.py works for Tetris-v0 but 
throws 
```
_self._did_step(done)
TypeError: _did_step() takes 1 positional argument but 2 were given.
```

I think there is issue with how the environment is wrapped for Mario. I will try to look deeper and fix the issue but help is appreciated.

**Comment by Kautenja** [comment]
Hmmm can you run the following script and let me know the output?

```python
import pkg_resources
print(pkg_resources.get_distribution("nes-py").version)
print(pkg_resources.get_distribution("gym-super-mario-bros").version)
```

My thought is that you have a version mix-match between these two packages

**Comment by Kautenja** [comment]
also what command are you running to start the training process?

**Comment by aadeshnpn** [comment]
I upgraded SuperMarioBro 3.0.5 to 3.0.8 and now the training it working. Thanks

**Comment by Kautenja** [comment]
whoops i meant to respond earlier but got buried in work projects. It's odd that 3.0.5 and 1.0.0 are interacting in this way (gym-super-mario-bros 3.0.5 should have the new API changes from nes-py 1.0.0), but it seems the newer versions resolve the problem. Closing issue.
